[package]
name = "the-crew-solver"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
enum_dispatch = "0.3.13"
rand = "0.9.2"
thiserror = "2.0.16"
